### ISSUE TITLE
不能正常运行

### ISSUE THREAD

**Issue by wangnuan7751** [lc4t/Bili-Live-Bot#13]
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\Administrator\Desktop\Bili-Live-Bot-master\Bili-Live-Bot-master\run.py", line 72, in init_users
    await notifier.add_user(user_info=user_info,
  File "C:\Users\Administrator\Desktop\Bili-Live-Bot-master\Bili-Live-Bot-master\notifier.py", line 295, in add_user
    await var_notifier.add_user(**kwargs)
  File "C:\Users\Administrator\Desktop\Bili-Live-Bot-master\Bili-Live-Bot-master\notifier.py", line 88, in add_user
    await self._users.add_user(**kwargs)
  File "C:\Users\Administrator\Desktop\Bili-Live-Bot-master\Bili-Live-Bot-master\notifier.py", line 56, in add_user
    user = User(
  File "C:\Users\Administrator\Desktop\Bili-Live-Bot-master\Bili-Live-Bot-master\user.py", line 42, in __init__
    self.gift_comb_delay = dict_user['gift_comb_delay']
KeyError: 'gift_comb_delay'

**Comment by lc4t** [comment]
这个问题是配置里面缺少gift_comb_delay
